export const mapConfig = {
  desktop: {
    backgroundImage: "/assets/bg_gradient_desktop.png",
    mapSrc: "/assets/map_desk.png",
    pinpoints: [
      {
        hoverEffect: "top-[110px] left-[0px] transform -translate-x-1/2",
        topPosition: "12%",
        leftPosition: "40.3%",
        location: "Paris, France",
        address: "38 Rue de Berri, 75008 Paris, France",
        phone: "+33 (0)1 47 14 72 38",
        email: "paris@solutionec.com",
        image: "/assets/building.png",
      },
      {
        hoverEffect: "top-[110px] left-[0px] transform -translate-x-1/2",
        topPosition: "13%",
        rightPosition: "53.5%",
        location: "Puteaux, France",
        address: "1 Parvis de la Défense, 92800 Puteaux, France",
        phone: "+33 (0)1 47 14 72 38",
        email: "puteaux@solutionec.com",
        image: "/assets/building.png",
      },
      {
        hoverEffect: "top-[110px] left-[0px] transform -translate-x-1/2",
        topPosition: "32%",
        rightPosition: "30.7%",
        location: "Bangalore, India",
        address:
          "Brigade Metropolis Summit Tower A, 6th Floor, GarudacharPalya, Mahadevapura, Bengaluru – 560048, India",
        phone: "+91 8976564534",
        email: "banglore@solutionec.com",
        image: "/assets/building.png",
      },
    ],
  },
  tablet: {
    backgroundImage: "/assets/bg_gradient_tab.png",
    mapSrc: "/assets/map_tablet.png",
    pinpoints: [
      {
        hoverEffect: "top-[110px] left-[0px] transform -translate-x-1/2",
        topPosition: "4%",
        leftPosition: "38.5%",
        location: "Paris, France",
        address: "38 Rue de Berri, 75008 Paris, France",
        phone: "+33 (0)1 47 14 72 38",
        email: "paris@solutionec.com",
        image: "/assets/building.png",
      },
      {
        hoverEffect: "top-[110px] left-[0px] transform -translate-x-1/2",
        topPosition: "11%",
        rightPosition: "52%",
        location: "Puteaux, France",
        address: "1 Parvis de la Défense, 92800 Puteaux, France",
        phone: "+33 (0)1 47 14 72 38",
        email: "puteaux@solutionec.com",
        image: "/assets/building.png",
      },
      {
        hoverEffect: "top-[100px] left-[0px] transform -translate-x-1/2",
        topPosition: "29%",
        rightPosition: "30%",
        location: "Bangalore, India",
        address:
          "Brigade Metropolis Summit Tower A, 6th Floor, GarudacharPalya, Mahadevapura, Bengaluru – 560048, India",
        phone: "+91 8976564534",
        email: "banglore@solutionec.com",
        image: "/assets/building.png",
      },
    ],
  },
  mobile: {
    backgroundImage: "/assets/bg_gradient_mobile.png",
    mapSrc: "/assets/map_mobile.png",
    pinpoints: [
      {
        hoverEffect: "top-[60px] left-[44px] transform -translate-x-1/2",
        topPosition: "-4%",
        leftPosition: "36%",
        location: "Paris, France",
        address: "38 Rue de Berri, 75008 Paris, France",
        phone: "+33 (0)1 47 14 72 38",
        email: "paris@solutionec.com",
        image: "/assets/building.png",
      },
      {
        hoverEffect: "top-[60px] left-[44px] transform -translate-x-1/2",
        topPosition: "11%",
        rightPosition: "49.5%",
        location: "Puteaux, France",
        address: "1 Parvis de la Défense, 92800 Puteaux, France",
        phone: "+33 (0)1 47 14 72 38",
        email: "puteaux@solutionec.com",
        image: "/assets/building.png",
      },
      {
        hoverEffect: "top-[110px] left-[-40px] transform -translate-x-1/2",
        topPosition: "26%",
        rightPosition: "27.4%",
        location: "Bangaluru, India",
        address:
          "Brigade Metropolis Summit Tower A, 6th Floor, GarudacharPalya, Mahadevapura, Bengaluru – 560048, India",
        phone: "+91 8976564534",
        email: "banglore@solutionec.com",
        image: "/assets/building.png",
      },
    ],
  },
};
